AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam-go

  Sample SAM Template for aws-sam-go

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Parameters:
  SourceBucketName:
    Type: String
    Default: "zipkero-img-resize-src"
#  DestinationBucketName:
#    Type: String
#    Default: "zipkero-img-resize-dest"

Resources:
  ImageResizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: image-resize/
      Handler: image-resize
      Runtime: go1.x
      Architectures:
        - x86_64
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref SourceBucketName
        - AWSLambdaBasicExecutionRole
        - CloudWatchLogsFullAccess
      Events:
        ImageResizeS3UploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref ImageUploadSrcBucket
            Events: s3:ObjectCreated:*

  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt ImageResizeFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: 's3.amazonaws.com'
      SourceAccount: !Sub ${AWS::AccountId}
      SourceArn: !GetAtt ImageUploadSrcBucket.Arn

  ImageUploadSrcBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SourceBucketName

#  ImageUploadDestBucket:
#    Type: AWS::S3::Bucket
#    Properties:
#      BucketName: !Ref SourceBucketName

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  ImageUploadSrcBucket:
    Description: s3 lambda trigger
    Value: !Ref ImageUploadSrcBucket
#  ImageUploadDestBucket:
#    Description: s3 lambda trigger
#    Value: !Ref ImageUploadDestBucket
  ImageResizeFunction:
    Description: First Lambda Function ARN
    Value: !GetAtt ImageResizeFunction.Arn
